
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.7 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xscaler.h"

/*
* The configuration table for devices
*/

XScaler_Config XScaler_ConfigTable[] =
{
	{
		XPAR_V_SCALER_0_DEVICE_ID,
		XPAR_V_SCALER_0_BASEADDR,
		XPAR_V_SCALER_0_NUM_V_TAPS,
		XPAR_V_SCALER_0_NUM_H_TAPS,
		XPAR_V_SCALER_0_MAX_PHASES,
		XPAR_V_SCALER_0_MAX_COEF_SETS,
		XPAR_V_SCALER_0_CHROMA_FORMAT,
		XPAR_V_SCALER_0_SEPARATE_YC_COEFS,
		XPAR_V_SCALER_0_SEPARATE_HV_COEFS
	}
};


